<?php
    $qGetPO = "SELECT tanggal, nama_suplier, P.nama, catatan, subtotal, potongan, total, ppn, meterai, tagihan FROM surat_pemesanan_non_medis SPN INNER JOIN ipsrssuplier S ON SPN.kode_suplier=S.kode_suplier INNER JOIN pegawai P ON SPN.nip=P.nik WHERE no_pemesanan='" . $params["id"] . "'";
    $getPO = mysqli_query($connect_app, $qGetPO);
    $PO = mysqli_fetch_assoc($getPO);
    $qGetPODtl = "SELECT DSPN.kode_brng, nama_brng, SB.satuan AS satuan_besar, Sum(jumlah) AS jumlah, h_pesan, Sum(subtotal) AS subtotal, dis, dis2, Sum(besardis) AS besardis, Sum(total) AS total FROM detail_surat_pemesanan_non_medis DSPN INNER JOIN ipsrsbarang B ON DSPN.kode_brng=B.kode_brng INNER JOIN kodesatuan SK ON DSPN.kode_sat=SK.kode_sat INNER JOIN kodesatuan SB ON DSPN.kode_satbesar=SB.kode_sat WHERE no_pemesanan='" . $params["id"] . "' GROUP BY kode_brng ORDER BY kode_brng";
    $getPODtl = mysqli_query($connect_app, $qGetPODtl);
    $lstPODtl = ""; $i = 0;
    while ($data = mysqli_fetch_assoc($getPODtl)) {
        $lstPODtl .= "<tr><td>" . ++$i . "</td><td>" . $data["kode_brng"] . "</td><td>" . $data["nama_brng"] . "</td><td>" . $data["jumlah"] . " " . $data["satuan_besar"] . "</td><td class='td-num'>" . number_format($data["h_pesan"], 0, ",", ".") . "</td><td class='td-num'>" . str_replace(".", ",", $data["dis"]) . "</td><td class='td-num'>" . str_replace(".", ",", $data["dis2"]) . "</td><td class='td-num'>" . number_format($data["besardis"], 0, ",", ".") . "</td><td class='td-num'>" . number_format($data["total"], 0, ",", ".") . "</td></tr>";
    }
    $lstPODtl = "<table class='report-table main-table table-border'><tr><th style='width: 25px'>No.</th><th style='width: 60px'>Kode</th><th>Nama Barang</th><th style='width: 50px'>Jumlah</th><th style='width: 70px'>Harga Per Satuan</th><th style='width: 56px'>Diskon 1 (%)</th><th style='width: 56px'>Diskon 2 (%)</th><th style='width: 70px'>Diskon (Rp)</th><th style='width: 80px'>Total</th></tr>" . $lstPODtl . "</table>";
    $lstPODtl .= "<table class='main-table'><tr><td>Subtotal : " . number_format($PO["subtotal"], 0, ",", ".") . " <span class='span-total'>|</span> Diskon : " . number_format($PO["potongan"], 0, ",", ".") . " <span class='span-total'>|</span> Total : " . number_format($PO["total"], 0, ",", ".") . " <span class='span-total'>|</span> PPN : " . number_format($PO["ppn"], 0, ",", ".") . " <span class='span-total'>|</span> Jumlah Tagihan : <strong>" . number_format($PO["tagihan"], 0, ",", ".") . "</strong></td></tr></table>";
    $title = "";
    $header = "<style>#kop-report { text-align: left; margin-left: 70px; } #nama-rs { font-size: 9pt; } </style><span style='font-size: 12pt; position: absolute; right: 0; top: 0'>SURAT PEMESANAN BARANG</span><table style='border: 1px solid black; position: absolute; right: 0; top: 20px'><tr><td>No. Pemesanan</td><td>: " . $params["id"] . "</td></tr><tr><td>Kepada</td><td>: " . $PO["nama_suplier"] . "</td></tr></table>Harap dikirim barang-barang tersebut di bawah ini:";
    $footer = "<br>Depok, " . date_format(date_create($PO["tanggal"]), "d-m-Y") . "<br><table style='text-align: center; vertical-align: top; display: inline'><tr><td>Dibuat Oleh</td><td style='width: 25px'></td><td>Mengetahui</td></tr><tr><td style='height: 20px'></td></tr><tr><td>(Farida Hanem Lestari, S.Si, Apt)</td><td></td><td>(Boy Hadi Ismanto, M.Kes)</td></tr><tr><td style='border-top: 1px solid black'>Kepala Bagian Purchasing</td><td></td><td style='border-top: 1px solid black'>Wadir Adm & Umum</td></tr></table><div style='float: right; padding: 5px; width: 250px; height: 55px; border: 1px solid black; margin-right: 20px; overflow: hidden'>Catatan: " . (strlen($PO["catatan"]) ? $PO["catatan"] : "-") . "</div><br>Persyaratan:<ol style='padding-inline-start: 16px; margin-block-start: 0px; margin-block-end: 0px;'><li>Apabila barang dikirim terlambat lebih dari 1 (satu) hari, kami berhak membatalkan sepihak</li><li>Barang yang tidak sesuai dengan PO dan atau perjanjian tidak akan kami terima</li><li>PO ini harus dilampirkan pada waktu tukar faktur dan penagihan (Asli)</li></ol>";
    $rpt_content = $header . $lstPODtl . $footer;
?>