<?php
    $title = "Master Obat, Alkes, BHP";
    $subtitle = "";
    $qGetItem = "SELECT kode_brng, nama_brng, J.nama AS jenis, K.nama AS kategori, G.nama AS golongan, SK.satuan AS satuan_kecil, SB.satuan AS satuan_besar, isi, stokminimal, dasar, h_beli, ralan, kelas1, kelas2, kelas3, utama, vip, vvip, beliluar, jualbebas, karyawan FROM databarang B INNER JOIN kodesatuan SK ON B.kode_sat=SK.kode_sat INNER JOIN kodesatuan SB ON B.kode_satbesar=SB.kode_sat INNER JOIN jenis J ON B.kdjns=J.kdjns INNER JOIN kategori_barang K ON B.kode_kategori=K.kode INNER JOIN golongan_barang G ON B.kode_golongan=G.kode WHERE status='1' ORDER BY nama_brng";
    $getItem = mysqli_query($connect_app, $qGetItem);
    $lstItem = ""; $idx = 0;
    while ($data = mysqli_fetch_assoc($getItem)) {
        $lstItem .= "<tr><td>" . ++$idx . "</td><td>" . $data["kode_brng"] . "</td><td>" . $data["nama_brng"] . "</td><td>" . $data["jenis"] . "</td><td>" . $data["kategori"] . "</td><td>" . $data["golongan"] . "</td><td>" . $data["satuan_kecil"] . "</td><td>" . $data["satuan_besar"] . "</td><td>" . number_format($data["isi"], 0, ",", ".") . "</td><td>" . number_format($data["stokminimal"], 0, ",", ".") . "</td><td>" . number_format($data["dasar"], 0, ",", ".") . "</td><td>" . number_format($data["h_beli"], 0, ",", ".") . "</td><td>" . number_format($data["ralan"], 0, ",", ".") . "</td><td>" . number_format($data["kelas1"], 0, ",", ".") . "</td><td>" . number_format($data["kelas2"], 0, ",", ".") . "</td><td>" . number_format($data["kelas3"], 0, ",", ".") . "</td><td>" . number_format($data["utama"], 0, ",", ".") . "</td><td>" . number_format($data["vip"], 0, ",", ".") . "</td><td>" . number_format($data["vvip"], 0, ",", ".") . "</td><td>" . number_format($data["beliluar"], 0, ",", ".") . "</td><td>" . number_format($data["jualbebas"], 0, ",", ".") . "</td><td>" . number_format($data["karyawan"], 0, ",", ".") . "</td></tr>";
    }
    $table = "<table><tr><th>No</th><th>Kode Barang</th><th>Nama Barang</th><th>Jenis</th><th>Kategori</th><th>Golongan</th><th>SK</th><th>SB</th><th>Isi</th><th>Stok Minimal</th><th>Harga Dasar</th><th>Harga Beli</th><th>Rawat Jalan</th><th>Rawat Inap K1</th><th>Rawat Inap K2</th><th>Rawat Inap K3</th><th>Rawat Inap Utama</th><th>Rawat Inap VIP</th><th>Rawat Inap VVIP</th><th>Beli Luar</th><th>Jual Bebas</th><th>Karyawan</th></tr>" . $lstItem . "</table>";
?>